### ISSUE TITLE
BTCD and LTCD client

### ISSUE THREAD

**Issue by michael1011** [dopetard/walli-server#25]
The task is to write a client that can be reused for BTCD and LTCD and is capable of:
- ~~~generating new SegWit addresses~~~
- a listener to detect when a transaction sent to a specific address is confirmed
- broadcasting a transaction

**Comment by ImmanuelSegol** [comment]
Hi,
Should I use a package such as [https://github.com/ruimarinho/bitcoin-core](url),
or should I build my own module for configuring/connecting to the JSON RPC.

**Comment by michael1011** [comment]
The package you refereed to is for Bitcoin Core. I was planning to use [BTCD](https://github.com/btcsuite/btcd) because it is used most of the time in combination with LND. The problem with BTCD is that it doesn't include a wallet. But Bitcoin Core does and it would work with LND too. Any thoughts on that @dopetard? :thinking:

We could use an already existing API wrapper if it does everything I we need. It is up to you. 

But first we have to decide whether we should use BTCD or Bitcoin Core.

**Comment by dopetard** [comment]
I'd vouch for using BTCD. It's better to not drift too far away from something that has been proved working. The variables are already too many.

**Comment by michael1011** [comment]
Yeah sticking to BTCD makes sense. I updated my first comment accordingly. We will need to use an additional package for managing our addresses but that should be done in a separate PR.

@ImmanuelSegol you can find the documentation of the JSON-RPC [here](https://github.com/btcsuite/btcd/blob/master/docs/json_rpc_api.md). Feel free to send me a message on Gitter if you encounter any issues or have questions.
