### ISSUE TITLE
Parsing configuration files

### ISSUE THREAD

**Issue by michael1011** [dopetard/walli-server#46]
Right now we are parsing the config files of BTCD and LND and that works thank to #44. But we are explicitly getting the values we need from the config of the external service and not using the `deepMerge` function.

This issue is about:
- doing the configuration parsing properly in a generic way that will work with other nodes we might want to add in the future
- considering whether getting information about how to connect to these nodes from XUD directly via an API (because XUD will have to be connected to them too) is a good idea
- making the config parsing completely compatible with LND and BTCD (for example: if no port is specified in `listen` those services will append the default port internally and we should do that too)
- properly testing the configuration parsing so that we don't have to worry about it in the future

Those things could be split up into different issues and PRs if needed.

**Comment by ImmanuelSegol** [comment]
@michael1011 I'm a bit confused about the second bulletin, why would we want to get the info about `btcd` / `lnd` from `XUD`, after all, if I'm understanding correctly a user of `walli-server` will also have XUD installed on his computer?

**Comment by michael1011** [comment]
@ImmanuelSegol that was just a random idea of mine. We can revisit that later when we are actually doing swaps with XUD. Forget about it for now.

**Comment by ImmanuelSegol** [comment]
> @ImmanuelSegol that was just a random idea of mine. We can revisit that later when we are actually doing swaps with XUD. Forget about it for now.

@michael1011 Ok sounds cool 👍
