### ISSUE TITLE
Setup regtest environment

### ISSUE THREAD

**Issue by michael1011** [dopetard/walli-server#61]
We should [`regtest`](https://bitcoin.org/en/glossary/regression-test-mode) for developing (and also for integration tests in the future) because the `testnet` isn't reliable and we don't have a set up `simnet` currently.

This issue is about figuring out how to setup `regtest` with BTCD and how to use it for development and integration tests locally and on Travis.

**Comment by ImmanuelSegol** [comment]
I was thinking of making a docker container with `btcd`.
Docker allows for [local unit test](https://engineering.gosquared.com/testing-with-docker) and for integration with [Travis CI](https://docs.travis-ci.com/user/docker/).

**Comment by michael1011** [comment]
Did you check what LND is doing with their integration tests? @ImmanuelSegol
