### ISSUE TITLE
Implement Litecoin

### ISSUE THREAD

**Issue by michael1011** [dopetard/walli-server#9]
Related to: https://github.com/michael1011/xud/issues/2

It comes down to detect the currency by the prefix of the invoice and add an option to select the currency when getting a new invoice.

Because LND is compatible with just Bitcoin and Litecoin and ERC20 tokens won't be part of the prototype we don't need an API method to list all supported currencies for now? Are the engineers hardcoding the currencies?

@dopetard

**Comment by ImmanuelSegol** [comment]
@michael1011 Should I implement this?

**Comment by michael1011** [comment]
This issue is kind of deprecated. And we should revisit once we have a Submarine Swap working

**Comment by michael1011** [comment]
Deprecated
